/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koureio;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static koureio.Koureio.DPstatement;
import static koureio.Koureio.DdbConnection;
import static koureio.Koureio.Dstatement;
import static koureio.Koureio.rs;


/**
 *
 * @author KARIOTIS STEFANOS
 */
public  class User_Log extends javax.swing.JFrame {

    /**
     * Creates new form User_Log
     */
    public User_Log() throws Exception {
        initComponents();
        MyConnection();
        setSize(1010,680);
        setResizable(false);
        Koureio kour =new Koureio();
        usern.setText(kour.getUserLogIn());
        FirstSecond();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        third = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        UserLogOut2 = new javax.swing.JButton();
        DeleteRequest1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        time2 = new javax.swing.JLabel();
        hairdresser2 = new javax.swing.JLabel();
        hairdresser1_3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        day2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usern3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        second = new javax.swing.JPanel();
        UserLogOut1 = new javax.swing.JButton();
        DeleteRequest = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        time1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        day1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hairdresser1 = new javax.swing.JLabel();
        hairdresser1_2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        usern2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        first = new javax.swing.JPanel();
        UserLogOut = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usern = new javax.swing.JLabel();
        Send_Request = new javax.swing.JButton();
        time = new javax.swing.JComboBox();
        day = new javax.swing.JComboBox();
        hairdresser = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        third.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Hairdresser");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        third.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 120, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Day");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        third.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 40, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Hour");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        third.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 50, -1));

        UserLogOut2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        UserLogOut2.setForeground(new java.awt.Color(153, 0, 51));
        UserLogOut2.setText("LOG OUT");
        UserLogOut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLogOut2ActionPerformed(evt);
            }
        });
        third.add(UserLogOut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 170, 77));

        DeleteRequest1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        DeleteRequest1.setForeground(new java.awt.Color(153, 0, 51));
        DeleteRequest1.setText("DELETE REQUEST");
        DeleteRequest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRequest1ActionPerformed(evt);
            }
        });
        third.add(DeleteRequest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 540, 190, 70));

        time2.setBackground(new java.awt.Color(255, 255, 255));
        time2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        time2.setForeground(new java.awt.Color(204, 0, 0));
        time2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        hairdresser2.setBackground(new java.awt.Color(255, 255, 255));
        hairdresser2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        hairdresser2.setForeground(new java.awt.Color(204, 0, 0));
        hairdresser2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        hairdresser1_3.setBackground(new java.awt.Color(255, 255, 255));
        hairdresser1_3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        hairdresser1_3.setForeground(new java.awt.Color(204, 0, 0));
        hairdresser1_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("  Το αίτημα σας έγινε αποδεκτό");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        day2.setBackground(new java.awt.Color(255, 255, 255));
        day2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        day2.setForeground(new java.awt.Color(204, 0, 0));
        day2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(hairdresser1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(hairdresser2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(day2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(time2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hairdresser2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(time2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(day2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hairdresser1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        third.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 540, 200));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Bernard MT Condensed", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("WELCOME  ,");

        usern3.setFont(new java.awt.Font("Bernard MT Condensed", 2, 24)); // NOI18N
        usern3.setForeground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usern3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usern3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        third.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 340, 90));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/koureio/images/Retail_Barber Club Scissors Detail_1280px.jpg"))); // NOI18N
        third.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 670));

        second.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserLogOut1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        UserLogOut1.setForeground(new java.awt.Color(153, 0, 0));
        UserLogOut1.setText("LOG OUT");
        UserLogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLogOut1ActionPerformed(evt);
            }
        });
        second.add(UserLogOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 182, 77));

        DeleteRequest.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        DeleteRequest.setForeground(new java.awt.Color(153, 0, 0));
        DeleteRequest.setText("DELETE REQUEST");
        DeleteRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRequestActionPerformed(evt);
            }
        });
        second.add(DeleteRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 180, 77));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        time1.setBackground(new java.awt.Color(255, 255, 255));
        time1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        time1.setForeground(new java.awt.Color(153, 0, 51));
        time1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("Hour");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        day1.setBackground(new java.awt.Color(255, 255, 255));
        day1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        day1.setForeground(new java.awt.Color(153, 0, 51));
        day1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("Day");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("Hairdresser");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        hairdresser1.setBackground(new java.awt.Color(255, 255, 255));
        hairdresser1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hairdresser1.setForeground(new java.awt.Color(153, 0, 51));
        hairdresser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        hairdresser1_2.setBackground(new java.awt.Color(255, 255, 255));
        hairdresser1_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hairdresser1_2.setForeground(new java.awt.Color(153, 0, 51));
        hairdresser1_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("Το αίτημά σας έχει σταλεί επιτυχώς και βρίσκεται σε αναμονή");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(hairdresser1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(hairdresser1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(day1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(98, 98, 98)))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(time1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))))
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hairdresser1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(time1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(hairdresser1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        second.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 740, 210));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Bernard MT Condensed", 2, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 0, 0));
        jLabel15.setText("WELCOME  ,");

        usern2.setFont(new java.awt.Font("Bernard MT Condensed", 2, 24)); // NOI18N
        usern2.setForeground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usern2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usern2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        second.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 340, 90));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/koureio/images/Retail_Barber Club Scissors Detail_1280px.jpg"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        second.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 650));

        first.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserLogOut.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        UserLogOut.setForeground(new java.awt.Color(102, 0, 0));
        UserLogOut.setText("LOG OUT");
        UserLogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        UserLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLogOutActionPerformed(evt);
            }
        });
        first.add(UserLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 180, 77));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("WELCOME  ,");

        usern.setFont(new java.awt.Font("Bernard MT Condensed", 2, 24)); // NOI18N
        usern.setForeground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usern, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usern, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        first.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 340, 90));

        Send_Request.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Send_Request.setForeground(new java.awt.Color(102, 0, 0));
        Send_Request.setText("SEND REQUEST");
        Send_Request.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Send_Request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Send_RequestActionPerformed(evt);
            }
        });
        first.add(Send_Request, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, 180, 77));

        time.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        time.setForeground(new java.awt.Color(102, 0, 0));
        time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        time.setEnabled(false);
        first.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 340, 140, 45));

        day.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        day.setForeground(new java.awt.Color(102, 0, 0));
        day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Day", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", " " }));
        day.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        day.setEnabled(false);
        day.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dayItemStateChanged(evt);
            }
        });
        first.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 335, 180, 50));

        hairdresser.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        hairdresser.setForeground(new java.awt.Color(102, 0, 0));
        hairdresser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Hairdresser", "Δημήτρης Πατραμάνης", "Μηνάς Χατζισάββας" }));
        hairdresser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        hairdresser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hairdresserItemStateChanged(evt);
            }
        });
        hairdresser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairdresserActionPerformed(evt);
            }
        });
        first.add(hairdresser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 290, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 0));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/koureio/images/Retail_Barber Club Scissors Detail_1280px.jpg"))); // NOI18N
        first.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(first, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(second, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(third, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(first, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(second, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(third, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLogOutActionPerformed
        Koureio kour=null;
        try {
            kour = new Koureio();
        } catch (Exception ex) {
            Logger.getLogger(Koureio.class.getName()).log(Level.SEVERE, null, ex);
        }
        kour.setVisible(true);
        try {
            DdbConnection.close();
        } catch (SQLException ex) {
            Logger.getLogger(User_Log.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_UserLogOutActionPerformed

    private void Send_RequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Send_RequestActionPerformed
        if(time.isEnabled()){
            String UpdateString="Insert into Request(username,hid,time,day) VALUES(?,?,?,?)";
            try{
                DPstatement = DdbConnection.prepareStatement(UpdateString);
                DPstatement.setString(1,usern.getText());
                DPstatement.setInt(2,(hairdresser.getSelectedIndex()));
                DPstatement.setString(4,week[day.getSelectedIndex()-1]);
                DPstatement.setString(3,((String)time.getSelectedItem()));
                int n= DPstatement.executeUpdate();
                Requestsuccess();

            }catch(SQLException ex){
                System.out.println("\n -- SQL Exception --- \n");
                while(ex != null) {
                    System.out.println("Message: " + ex.getMessage());
                    System.out.println("SQLState: " + ex.getSQLState());
                    System.out.println("ErrorCode: " + ex.getErrorCode());
                    ex = ex.getNextException();
                    System.out.println("");
                }
            }
            finally{
                try {
                    UpdateString="UPDATE Availability SET avail='no' where hid=? and time=? and day=?";
                    DPstatement = DdbConnection.prepareStatement(UpdateString);
                    DPstatement.setInt(1,(hairdresser.getSelectedIndex()));
                    DPstatement.setString(2,((String)time.getSelectedItem()));
                    DPstatement.setString(3,week[day.getSelectedIndex()-1]);
                    int n= DPstatement.executeUpdate();
                    DPstatement.close();
                    FirstSecond();
                } catch (SQLException ex) {
                    Logger.getLogger(User_Log.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_Send_RequestActionPerformed

    private void dayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dayItemStateChanged
        time.setEnabled(true);
        time.removeAllItems();
        String UpdateString ="Select time from AVAILABILITY "
        + " where hid ='"+(hairdresser.getSelectedIndex())+"' and day ='"+week[day.getSelectedIndex()-1]+"' and avail='yes'";
        try{
            Dstatement = DdbConnection.createStatement();
            rs= Dstatement.executeQuery(UpdateString);
            while(rs.next()){
                String time1=rs.getString("time");
                time.addItem(time1);
            }
        }catch(SQLException ex){
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
                System.out.println("Message: " + ex.getMessage());
                System.out.println("SQLState: " + ex.getSQLState());
                System.out.println("ErrorCode: " + ex.getErrorCode());
                ex = ex.getNextException();
                System.out.println("");
            }
        }
        finally{
            try {
                Dstatement.close();
            } catch (SQLException ex) {
                Logger.getLogger(User_Log.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_dayItemStateChanged

    private void hairdresserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairdresserActionPerformed

    }//GEN-LAST:event_hairdresserActionPerformed

    private void hairdresserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hairdresserItemStateChanged
        day.setEnabled(true);
        time.setEnabled(false);
        time.removeAllItems();
    }//GEN-LAST:event_hairdresserItemStateChanged

    private void UserLogOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLogOut1ActionPerformed
        Koureio kour=null;
        try {
            kour = new Koureio();
        } catch (Exception ex) {
            Logger.getLogger(Koureio.class.getName()).log(Level.SEVERE, null, ex);
        }
        kour.setVisible(true);
        try {
            DdbConnection.close();
        } catch (SQLException ex) {
            Logger.getLogger(User_Log.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_UserLogOut1ActionPerformed

    private void DeleteRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRequestActionPerformed
         first.setVisible(true);
         second.setVisible(false);
          try {
                   String UpdateString="UPDATE Availability SET avail='yes' where hid=? and time=? and day=?";
                    DPstatement = DdbConnection.prepareStatement(UpdateString);
                    DPstatement.setInt(1,(hairdresser.getSelectedIndex()));
                    DPstatement.setString(2,((String)time.getSelectedItem()));
                    DPstatement.setString(3,week[day.getSelectedIndex()-1]);
                    int n= DPstatement.executeUpdate();
                    UpdateString="Delete from Request where username=?";
                    DPstatement = DdbConnection.prepareStatement(UpdateString);
                    DPstatement.setString(1,usern2.getText());
                    n= DPstatement.executeUpdate();
                    Requestfail();
                    FirstSecond();
                }catch(SQLException ex){
         System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
                System.out.println("Message: " + ex.getMessage());
                System.out.println("SQLState: " + ex.getSQLState());
                System.out.println("ErrorCode: " + ex.getErrorCode());
                ex = ex.getNextException();
                System.out.println("");
            }
        }
        finally{
            try {
                
                DPstatement.close();
            } catch (SQLException ex) {
                Logger.getLogger(User_Log.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         
    }//GEN-LAST:event_DeleteRequestActionPerformed

    private void UserLogOut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLogOut2ActionPerformed
        Koureio kour=null;
        try {
            kour = new Koureio();
        } catch (Exception ex) {
            Logger.getLogger(Koureio.class.getName()).log(Level.SEVERE, null, ex);
        }
        kour.setVisible(true);
        try {
            DdbConnection.close();
        } catch (SQLException ex) {
            Logger.getLogger(User_Log.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_UserLogOut2ActionPerformed

    private void DeleteRequest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRequest1ActionPerformed
        first.setVisible(true);
         second.setVisible(false);
          try {
                    int hid=0;
                    String UpdateString="Select hid from HAIRDRESSER where name=? and surname=?";
                    DPstatement = DdbConnection.prepareStatement(UpdateString);
                    DPstatement.setString(1,hairdresser2.getText());
                    DPstatement.setString(2,hairdresser1_3.getText());
                    rs= DPstatement.executeQuery();
                    while(rs.next()){
                        hid=rs.getInt("hid");
                    }
                    UpdateString="UPDATE Availability SET avail='yes' where hid=? and time=? and day=?";
                    DPstatement = DdbConnection.prepareStatement(UpdateString);
                    DPstatement.setInt(1,hid);
                    DPstatement.setString(2,time2.getText());
                    DPstatement.setString(3,day2.getText());
                    int n= DPstatement.executeUpdate();
                    UpdateString="Delete from Appointment where username=?";
                    DPstatement = DdbConnection.prepareStatement(UpdateString);
                    DPstatement.setString(1,usern2.getText());
                    n= DPstatement.executeUpdate();
                    FirstSecond();
                    Requestfail();
                }catch(SQLException ex){
         System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
                System.out.println("Message: " + ex.getMessage());
                System.out.println("SQLState: " + ex.getSQLState());
                System.out.println("ErrorCode: " + ex.getErrorCode());
                ex = ex.getNextException();
                System.out.println("");
            }
        }
        finally{
            try {
                DPstatement.close();
            } catch (SQLException ex) {
                Logger.getLogger(User_Log.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_DeleteRequest1ActionPerformed

   static String     DdriverClassName = "org.apache.derby.jdbc.ClientDriver" ;
       static String     Durl = "jdbc:derby://localhost:1527/Koureio" ;
       static Connection DdbConnection = null;
       static String     Dusername = "tejohny";
       static String     Dpasswd = "margoleta16";
       static Statement  Dstatement       = null;
       static PreparedStatement DPstatement =null; 
       static ResultSet rs=null;
       static String week[] ={"Monday","Tuesday","Wednesday","Thursday","Friday"};
       
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new User_Log().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(User_Log.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    
    //Connection Section

    void MyConnection() throws Exception{
       try{ 
        Class.forName (DdriverClassName); 
       }catch(ClassNotFoundException ex){
       }
        System.out.println(Dusername + " "+ Dpasswd+" "+ Durl);
        DdbConnection = DriverManager.getConnection (Durl, Dusername, Dpasswd);
    }
    //
    
    void FirstSecond(){
        String UpdateString ="Select username from Request where username=?";
        String username1="";
         String UpdateString1 ="Select username from Appointment where username=?";
        String username2="";
        try{
         DPstatement = DdbConnection.prepareStatement(UpdateString);
         DPstatement.setString(1,usern.getText());
         rs= DPstatement.executeQuery();
         while(rs.next()){
             username1=rs.getString("username");
         }
         DPstatement = DdbConnection.prepareStatement(UpdateString1);
         DPstatement.setString(1,usern.getText());
         rs= DPstatement.executeQuery();
         while(rs.next()){
             username2=rs.getString("username");
         }
         if(username1.equals(usern.getText())){
             first.setVisible(false);
             second.setVisible(true);
             UserLogOut1.setVisible(true);
             DeleteRequest.setVisible(true);
             UserLogOut2.setVisible(false);
             DeleteRequest1.setVisible(false);
             usern2.setText(usern.getText());
             UpdateString ="Select H.name,H.surname,R.day,R.time from Request R"
                     + " join Hairdresser H on R.hid=H.hid where username=?";
             DPstatement = DdbConnection.prepareStatement(UpdateString);
             DPstatement.setString(1,usern.getText());
             rs=DPstatement.executeQuery();
              while(rs.next()){
                    String hairname= rs.getString("name");
                    String hairsurname= rs.getString("surname");
                    String dayd= rs.getString("day");
                    String timed= rs.getString("time");
                    hairdresser1.setText(hairname);
                    hairdresser1_2.setText(hairsurname);
                    day1.setText(dayd);
                    time1.setText(timed);
                }
         }else if(username2.equals(usern.getText())){
             first.setVisible(false);
             second.setVisible(false);
             third.setVisible(true);
             UserLogOut1.setVisible(false);
             DeleteRequest.setVisible(false);
             UserLogOut2.setVisible(true);
             DeleteRequest1.setVisible(true);
             usern2.setText(usern.getText());
             UpdateString ="Select H.name,H.surname,R.day,R.time from Appointment R"
                     + " join Hairdresser H on R.hid=H.hid where username=?";
             DPstatement = DdbConnection.prepareStatement(UpdateString);
             DPstatement.setString(1,usern.getText());
             rs=DPstatement.executeQuery();
              while(rs.next()){
                    String hairname= rs.getString("name");
                    String hairsurname= rs.getString("surname");
                    String dayd= rs.getString("day");
                    String timed= rs.getString("time");
                    hairdresser2.setText(hairname);
                    hairdresser1_3.setText(hairsurname);
                    day2.setText(dayd);
                    time2.setText(timed);
                }
         }
         else{
           try{  
            first.setVisible(true);
             second.setVisible(false); 
             third.setVisible(false);
             hairdresser.setSelectedIndex(0);
             day.setSelectedIndex(0);        
           }catch(Exception e){
               
           } 
         }
        }catch(SQLException ex){
         System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
                System.out.println("Message: " + ex.getMessage());
                System.out.println("SQLState: " + ex.getSQLState());
                System.out.println("ErrorCode: " + ex.getErrorCode());
                ex = ex.getNextException();
                System.out.println("");
            }
        }
        finally{
            try {
                DPstatement.close();
            } catch (SQLException ex) {
                Logger.getLogger(User_Log.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
     public void Requestsuccess(){
    JOptionPane.showMessageDialog(null,"REQUEST WAS SEND","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
    }
     public void Requestfail(){
    JOptionPane.showMessageDialog(null,"YOUR REQUEST WAS DELETED","",JOptionPane.INFORMATION_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteRequest;
    private javax.swing.JButton DeleteRequest1;
    private javax.swing.JButton Send_Request;
    private javax.swing.JButton UserLogOut;
    private javax.swing.JButton UserLogOut1;
    private javax.swing.JButton UserLogOut2;
    private javax.swing.JComboBox day;
    private javax.swing.JLabel day1;
    private javax.swing.JLabel day2;
    private javax.swing.JPanel first;
    private javax.swing.JComboBox hairdresser;
    private javax.swing.JLabel hairdresser1;
    private javax.swing.JLabel hairdresser1_2;
    private javax.swing.JLabel hairdresser1_3;
    private javax.swing.JLabel hairdresser2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel second;
    private javax.swing.JPanel third;
    private javax.swing.JComboBox time;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel time2;
    private javax.swing.JLabel usern;
    private javax.swing.JLabel usern2;
    private javax.swing.JLabel usern3;
    // End of variables declaration//GEN-END:variables
}
